export const hyperblogsCopy = {
  title: "Hyperblog Library",
  description:
    "View and create Hyperblogs from the Bonfires. Hyperblog content is generated by AI, informed by the sponsor's graph and paid for using x402 payments on Base.",
  dataroomTitle: "Datarooms",
  dataroomDescription: "Datarooms provide a specific focus and theme for Hyperblog creators to choose from. You may view existing Hyperblogs generated in each Dataroom, or create your own.",
  dataroomTooltipContent: ["A dataroom represents a designated \"focus\" node on the Bonfire graph that the Hyperblogs are generated from.",  "Clicking \"Explore Graph\" will take you to the Explorer with the dataroom node as its center."],
  createTitle: "Create Blog",
  createDescription: "Generate an AI-powered blog post from this dataroom's knowledge graph",
  createTooltipContent: "Describe what you want the content to be about; mention specific topics, themes or subjects if you wish to see them in the blog.",
  createDescriptionPlaceholder: "Describe what you want the blog to cover (Max 600 characters)",
};
