export const heroCopy = {
  title: "Collective Sensemaking Experience",
  description:
    "Explore, visualize and interact with ETHBoulder's collective intelligence.",
  ctaPrimary: "Explore Graph",
  ctaSecondary: "Join ETH Boulder Telegram group",
};

// Static nodes: web3 conference–related terms with id, label, and size (1–5).
const NODES_DATA: { id: string; label: string; size: number }[] = [
  { id: "eth", label: "ETH", size: 5 },
  { id: "ethereum", label: "Ethereum", size: 5 },
  { id: "web3", label: "Web3", size: 5 },
  { id: "conference", label: "Conference", size: 4 },
  { id: "boulder", label: "Boulder", size: 4 },
  { id: "defi", label: "DeFi", size: 3 },
  { id: "dao", label: "DAO", size: 3 },
  { id: "smart-contracts", label: "Smart Contracts", size: 3 },
  { id: "nft", label: "NFT", size: 3 },
  { id: "hackathon", label: "Hackathon", size: 3 },
  { id: "workshop", label: "Workshop", size: 3 },
  { id: "governance", label: "Governance", size: 3 },
  { id: "layer2", label: "Layer 2", size: 3 },
  { id: "community", label: "Community", size: 3 },
  { id: "wallet", label: "Wallet", size: 2 },
  { id: "builders", label: "Builders", size: 2 },
  { id: "zk", label: "ZK", size: 2 },
  { id: "rollups", label: "Rollups", size: 2 },
  { id: "networking", label: "Networking", size: 2 },
  { id: "devcon", label: "Devcon", size: 2 },
  { id: "eip", label: "EIP", size: 1 },
  { id: "dapp", label: "DApp", size: 1 },
  { id: "token", label: "Token", size: 1 },
  { id: "staking", label: "Staking", size: 1 },
  { id: "grants", label: "Grants", size: 1 },
  { id: "mev", label: "MEV", size: 2 },
  { id: "gas", label: "Gas", size: 2 },
  { id: "validator", label: "Validator", size: 2 },
  { id: "pos", label: "PoS", size: 2 },
  { id: "colorado", label: "Colorado", size: 3 },
  { id: "speaker", label: "Speaker", size: 2 },
  { id: "sponsor", label: "Sponsor", size: 2 },
  { id: "open-source", label: "Open Source", size: 3 },
  { id: "security", label: "Security", size: 2 },
  { id: "audits", label: "Audits", size: 2 },
  { id: "ens", label: "ENS", size: 2 },
  { id: "identity", label: "Identity", size: 2 },
  { id: "refi", label: "ReFi", size: 2 },
  { id: "dex", label: "DEX", size: 2 },
  { id: "liquidity", label: "Liquidity", size: 2 },
  { id: "voting", label: "Voting", size: 2 },
  { id: "treasury", label: "Treasury", size: 2 },
  { id: "protocol", label: "Protocol", size: 2 },
  { id: "ipfs", label: "IPFS", size: 2 },
  { id: "innovation", label: "Innovation", size: 2 },
  { id: "gaming", label: "Gaming", size: 2 },
  { id: "denver", label: "Denver", size: 1 },
  { id: "attendee", label: "Attendee", size: 1 },
  { id: "research", label: "Research", size: 1 },
  { id: "sustainability", label: "Sustainability", size: 1 },
];

// Links by node id (source -> target). Interrelation defines edges.
const LINKS_DATA: { source: string; target: string }[] = [
  { source: "eth", target: "ethereum" },
  { source: "eth", target: "smart-contracts" },
  { source: "eth", target: "defi" },
  { source: "eth", target: "dao" },
  { source: "eth", target: "nft" },
  { source: "ethereum", target: "web3" },
  { source: "ethereum", target: "layer2" },
  { source: "web3", target: "conference" },
  { source: "conference", target: "boulder" },
  { source: "conference", target: "hackathon" },
  { source: "conference", target: "workshop" },
  { source: "conference", target: "networking" },
  { source: "conference", target: "community" },
  { source: "boulder", target: "hackathon" },
  { source: "boulder", target: "community" },
  { source: "defi", target: "dao" },
  { source: "defi", target: "token" },
  { source: "defi", target: "staking" },
  { source: "defi", target: "smart-contracts" },
  { source: "dao", target: "governance" },
  { source: "dao", target: "token" },
  { source: "smart-contracts", target: "dapp" },
  { source: "smart-contracts", target: "nft" },
  { source: "layer2", target: "rollups" },
  { source: "layer2", target: "zk" },
  { source: "rollups", target: "zk" },
  { source: "hackathon", target: "builders" },
  { source: "hackathon", target: "grants" },
  { source: "workshop", target: "builders" },
  { source: "community", target: "builders" },
  { source: "ethereum", target: "eip" },
  { source: "devcon", target: "conference" },
  { source: "wallet", target: "eth" },
  { source: "wallet", target: "dapp" },
  { source: "boulder", target: "colorado" },
  { source: "colorado", target: "denver" },
  { source: "conference", target: "speaker" },
  { source: "conference", target: "sponsor" },
  { source: "conference", target: "attendee" },
  { source: "sponsor", target: "grants" },
  { source: "ethereum", target: "pos" },
  { source: "pos", target: "validator" },
  { source: "pos", target: "staking" },
  { source: "eth", target: "gas" },
  { source: "eth", target: "mev" },
  { source: "mev", target: "defi" },
  { source: "smart-contracts", target: "security" },
  { source: "smart-contracts", target: "audits" },
  { source: "security", target: "audits" },
  { source: "ens", target: "identity" },
  { source: "ens", target: "ethereum" },
  { source: "identity", target: "web3" },
  { source: "defi", target: "dex" },
  { source: "defi", target: "liquidity" },
  { source: "dex", target: "liquidity" },
  { source: "dao", target: "voting" },
  { source: "dao", target: "treasury" },
  { source: "governance", target: "voting" },
  { source: "governance", target: "treasury" },
  { source: "web3", target: "open-source" },
  { source: "open-source", target: "innovation" },
  { source: "hackathon", target: "innovation" },
  { source: "builders", target: "research" },
  { source: "refi", target: "sustainability" },
  { source: "refi", target: "web3" },
  { source: "nft", target: "gaming" },
  { source: "dapp", target: "gaming" },
  { source: "ethereum", target: "protocol" },
  { source: "layer2", target: "protocol" },
  { source: "ipfs", target: "web3" },
  { source: "ipfs", target: "nft" },
  { source: "workshop", target: "innovation" },
  { source: "workshop", target: "research" },
  { source: "networking", target: "community" },
  { source: "networking", target: "attendee" },
  { source: "speaker", target: "workshop" },
  { source: "speaker", target: "community" },
  { source: "attendee", target: "community" },
  { source: "attendee", target: "networking" },
  { source: "devcon", target: "ethereum" },
  { source: "devcon", target: "boulder" },
  { source: "eip", target: "protocol" },
  { source: "eip", target: "smart-contracts" },
  { source: "token", target: "liquidity" },
  { source: "token", target: "dex" },
  { source: "validator", target: "ethereum" },
  { source: "validator", target: "staking" },
  { source: "gas", target: "smart-contracts" },
  { source: "gas", target: "dapp" },
  { source: "mev", target: "rollups" },
  { source: "mev", target: "liquidity" },
  { source: "security", target: "dapp" },
  { source: "audits", target: "defi" },
  { source: "identity", target: "dao" },
  { source: "identity", target: "dapp" },
  { source: "refi", target: "dao" },
  { source: "dex", target: "smart-contracts" },
  { source: "voting", target: "token" },
  { source: "protocol", target: "smart-contracts" },
  { source: "innovation", target: "research" },
  { source: "gaming", target: "community" },
  { source: "gaming", target: "builders" },
  { source: "builders", target: "community" },
  { source: "builders", target: "open-source" },
  { source: "zk", target: "security" },
  { source: "zk", target: "layer2" },
  { source: "rollups", target: "ethereum" },
  { source: "ipfs", target: "dapp" },
  { source: "grants", target: "builders" },
  { source: "grants", target: "innovation" },
  { source: "wallet", target: "identity" },
  { source: "ens", target: "wallet" },
  { source: "treasury", target: "grants" },
  { source: "sustainability", target: "refi" },
  { source: "denver", target: "colorado" },
  { source: "boulder", target: "denver" },
];

export const staticGraphNodes = {
  NODES_DATA,
  LINKS_DATA,
};
